trainer:
  nnodes: 1
  n_gpus_per_node: 4
  max_colocate_count: 10

data:
  path: /home/chenzhb/Workspaces/verl/data/logiqa/train.parquet
  prompt_key: prompt
  prompt_path: /home/chenzhb/Workspaces/verl/prompts/base.txt
  batch_size: 64

model:
  path: /home/chenzhb/Workspaces/LLMs/Qwen3-8B-Base
  external_lib: null

rollout:
  name: vllm
  mode: sync
  temperature: 0.8
  top_k: -1
  top_p: 1.0
  prompt_length: 1024
  response_length: 2048
  dtype: bfloat16
  gpu_memory_utilization: 0.5
  ignore_eos: False
  enforce_eager: True
  free_cache_engine: True
  load_format: dummy_dtensor
  tensor_model_parallel_size: 4
  max_num_batched_tokens: 8192
  max_model_len: 8192
  max_num_seqs: 1024
  log_prob_micro_batch_size: null
  log_prob_micro_batch_size_per_gpu: 8
  use_fire_sampling: False
  do_sample: True
  disable_log_stats: True
  enable_chunked_prefill: True
  n: 64

actor:
  strategy: fsdp
  ulysses_sequence_parallel_size: 1
  fsdp_config:
    fsdp_size: -1

filter:
  output_dir: /home/chenzhb/Workspaces/verl/data/logiqa_sft
  correct_size: 500
  error_size: 500
  generated_path: null
  run_generation: True
  save_generations: True

ray_init:
  num_cpus: null
