#!/usr/bin/env bash
set -x

HOME=/home/chenzhb/Workspaces/verl
MODEL_PATH=/home/chenzhb/Workspaces/LLMs/Qwen3-8B-Base
N_GPUS_PER_NODE=2

M=6
N=2
L=1
T=2
NUM_TRACES=16

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=step_treerl_grpo \
    algorithm.use_kl_in_reward=False \
    data.train_files=$HOME/data/logiqa_global_fol_prm/train.parquet \
    data.val_files=$HOME/data/logiqa/validate.parquet \
    data.train_batch_size=4 \
    data.max_prompt_length=2048 \
    data.max_response_length=2048 \
    data.filter_overlong_prompts=True \
    data.truncation=error \
    data.prompt_path=$HOME/prompts/premise_conclusion.txt \
    actor_rollout_ref.model.path=${MODEL_PATH} \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.policy_loss=tree_loss \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=4 \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=16384 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.loss_agg_mode=seq-mean-token-mean \
    actor_rollout_ref.actor.kl_loss_coef=0.0001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${N_GPUS_PER_NODE} \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.max_model_len=8192 \
    actor_rollout_ref.rollout.n=${M} \
    actor_rollout_ref.rollout.temperature=0.8 \
    actor_rollout_ref.rollout.top_p=0.95 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.enable=False \
    reward_model.reward_manager=auto \
    reward_model.micro_batch_size_per_gpu=1 \
    reward_model.model.fsdp_config.optimizer_offload=True \
    reward_model.reward_kwargs.reward_style=null \
    trainer.val_before_train=False \
    trainer.sampling_strategy=step_treerl \
    trainer.process_reward.type=fol \
    trainer.process_reward.fol.prm_mode=global_fol_prm \
    trainer.process_reward.fol.metadata_path=$HOME/data/logiqa_global_fol_prm/fol_metadata.json \
    trainer.process_reward.fol.online_declaration_fallback=true \
    trainer.process_reward.fol.fail_on_missing_metadata=false \
    trainer.process_reward.fol.llm.provider=minimax \
    trainer.process_reward.fol.llm.api_base_url=https://api.minimaxi.com/v1 \
    trainer.process_reward.fol.llm.api_key='${oc.env:MINIMAX_API_KEY}' \
    trainer.process_reward.fol.llm.model_name=MiniMax-M2.7 \
    trainer.process_reward.fol.llm.max_concurrency=8 \
    trainer.step_treerl_config.max_depth=20 \
    trainer.step_treerl_config.max_token_num=4096 \
    trainer.step_treerl_config.branch_max_new_tokens=512 \
    trainer.step_treerl_config.m=${M} \
    trainer.step_treerl_config.n=${N} \
    trainer.step_treerl_config.l=${L} \
    trainer.step_treerl_config.t=${T} \
    trainer.step_treerl_config.selected_num_traces=${NUM_TRACES} \
    trainer.step_treerl_config.path_selection=selected_terminals \
    trainer.step_treerl_config.use_weighted_value=true \
    trainer.step_treerl_config.weighted_value_style=sqrt \
    trainer.step_treerl_config.overall_norm_style=none \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name=verl \
    trainer.experiment_name=LogiQA_Qwen3-8B-base_StepTreeRL_fol_reward \
    trainer.n_gpus_per_node=${N_GPUS_PER_NODE} \
    trainer.nnodes=1 \
    trainer.save_freq=100000000 \
    trainer.test_freq=20 \
    trainer.max_actor_ckpt_to_keep=1 \
    trainer.max_critic_ckpt_to_keep=1 \
    trainer.total_epochs=1 \
    "$@"
